groups.wheel.use.wheel.group              = true
groups.wheel.group.name                  = etc:admingroup  

# GrouperSystem is the built-in superuser — use for initial setup
grouper.bootstrap.admin.identifier       = ExampeleGroupersystem  #Rename to match what is in your compose.yaml

# Auto-create/update database schema on startup (dev only)
grouper.ddl.run.at.startup               = true
grouper.ddl.run.at.startup.safe          = false

grouperUi.contextPath                    = /grouper

grouperUi.allow.ui.users                 = true
loader.run.on.startup                    = false

