# File location:
# /opt/grouperContainer/slashRoot/opt/grouper/grouperWebapp/WEB-INF/classes/
#   grouper.hibernate.properties

hibernate.connection.driver_class = org.postgresql.Driver

# "grouper-postgres" is the container_name of the postgres service
# Containers on the same network reach each other by container_name
hibernate.connection.url      = jdbc:postgresql://postgres:5432/grouper  #Whatever your postgres container names put that here for the url.#
hibernate.connection.username = $examplename
hibernate.connection.password = $examplepassword

hibernate.dialect = org.hibernate.dialect.PostgreSQL10Dialect

# Connection pool settings
hibernate.c3p0.max_size        = 10
hibernate.c3p0.min_size        = 1
hibernate.c3p0.timeout         = 100
hibernate.c3p0.max_statements  = 0
hibernate.c3p0.idle_test_period = 100
hibernate.c3p0.acquire_increment = 1
hibernate.c3p0.validate        = false
